name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean verify serenity:aggregate

      - name: Serenity Report
        uses: actions/upload-artifact@v2
        with:
          name: serenity-report
          path: target/serenity-report

      - name: Update Report into Repo
        uses: ad-m/github-push-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop # Cambia esto según la rama en la que quieras actualizar el reporte
          directory: target/serenity-report # Ruta al directorio que contiene los reportes
