name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean test

      - name: Generate and Save Cucumber Report
        run: |
          mkdir -p target/reports
          mvn io.github.temyers:cucumber-reporting:5.5.0:cucumber-report -Dcucumber.reporting.config.prettyReport=true -Dcucumber.reporting.config.jsonReportPaths="target/cucumber-reports/report.json"
          mv target/cucumber-reports/report.html target/reports
        continue-on-error: true
