name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean test

      - name: Generate and Save Allure Report
        run: |
          mkdir -p target/allure-results
          mvn clean test allure:report
          mv target/site/allure-maven-plugin/* target/reports
        continue-on-error: true
